### ISSUE TITLE
nullable

### ISSUE THREAD

**Issue by pjb1008** [microsoft/OpenAPI.NET.OData#162]
Hi,

A lot of schema are showing as having nullable items in contexts where this doesn't make a lot of sense.
Example:
```
    microsoft.graph.serviceUpdateMessage:
     ...
            services:
              type: array
              items:
                type: string
                nullable: true
              description: The affected services by the service message.
```
So that's an array of optional strings, which makes little sense. 

I am not sure if the graph metadata is wrong, of it the nullable appeared in the translation to OpenAPI.
