### ISSUE TITLE
required and additionalProperties not set

### ISSUE THREAD

**Issue by pjb1008** [microsoft/OpenAPI.NET.OData#163]
Hi,

When an Schema Object of type 'object' is declared in OpenAPI, the default behaviour is that properties are allowed to be missed out (I don't mean null, I mean not present at all). This is rarely desirable, so most schema of type 'object' will have ```required``` set to make sure that all property names are present.

Conversely, additional properties, not named in the schema,  are allowed to be present, with any type definition. For most applications, I would expect that to be disabled by setting ```additionalProperties: false```

Example - for this definition:
```
   microsoft.graph.identity:
      title: identity
      type: object
      properties:
        displayName:
          type: string
          description: 'The identity''s display name. Note that this may not always be available or up to date. For exam\
ple, if a user changes their display name, the API may show the new value in a future response, but the items associated\
 with the user won''t show up as having changed when using delta.'
          nullable: true
        id:
          type: string
          description: Unique identifier for the identity.
          nullable: true
```
I would like to add:
```
      required: ['displayName', 'id']
      additionalProperties: false
```

The purpose of this change is to prevent code generators that are aware of missing/extra properties from producing needlessly complicated code.
