### ISSUE TITLE
$expand is reported as enum while it is actually string

### ISSUE THREAD

**Issue by sherlock1982** [microsoft/OpenAPI.NET.OData#197]
Current behavior:
$expand is enum.

Expected behavior:
$expand is string because you can have complex expressions in $expand like for example `$expand=Groups($expand=Members)`

**Comment by darrelmiller** [comment]
If we updated the schema to be like this it would allow us to provide a list of properties that are expandable but also indicate that each expand property could be a more complex syntax.

```yaml
          schema:
            uniqueItems: true
            type: array
            items:
              anyOf:
                - enum:
                    - '*'
                    - serviceAnnouncement
                - type: string
              type: string
```

Thoughts?
