### ISSUE TITLE
Discriminator object refers to missing property

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#243]
Latest update of the conversion library includes adding some discriminator mappings to the openApi document. Possibly related to changes fixing https://github.com/microsoft/OpenAPI.NET.OData/issues/233

Taking a look at the previous description of the `apiAuthenticationConfigurationBase`

```yaml
    microsoft.graph.apiAuthenticationConfigurationBase:
      title: apiAuthenticationConfigurationBase
      type: object
```

And the new description 

``` yaml
    microsoft.graph.apiAuthenticationConfigurationBase:
      title: apiAuthenticationConfigurationBase
      type: object
      discriminator:
        propertyName: '@odata.type'
        mapping:
          '#microsoft.graph.basicAuthentication': '#/components/schemas/microsoft.graph.basicAuthentication'
          '#microsoft.graph.clientCertificateAuthentication': '#/components/schemas/microsoft.graph.clientCertificateAuthentication'
          '#microsoft.graph.pkcs12Certificate': '#/components/schemas/microsoft.graph.pkcs12Certificate'
```

The discriminator mapping mentions the propertyName `@odata.type` but the property collection (this instance has no properties) does not contain the property `@odata.type`. 

This leads to validation errors as described in https://github.com/microsoft/kiota/issues/1668. 

The conversion library should probably make sure the property exists before adding the mapping.
