### ISSUE TITLE
Support for enum flags

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#258]
Taking a look at the metadata for the `SourceType` enum in the graph metadata, there exists the `IsFlags` property which is set to true.

```xml
      <EnumType Name="sourceType" IsFlags="true">
        <Member Name="mailbox" Value="1" />
        <Member Name="site" Value="2" />
      </EnumType>
```
The `flags` attribute is not propagated to the converted openApi description in any way at the moment and also information on the values is also lost in the conversion process. 

```yaml
    microsoft.graph.security.sourceType:
      title: sourceType
      enum:
        - mailbox
        - site
        - unknownFutureValue
      type: string
```

This poses a challenge to Kiota at the moment as there is no signal for the generator to generate an appropriate Flag property. 

**Notes**
- According to https://github.com/OAI/OpenAPI-Specification/issues/348#issuecomment-336194030 enums could be better described to cater for values by conforming to the json schema
- Some extensions like `x-enumFlags` to denote flagged enums
- AutoRest uses `[x-ms-enum](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-enum)` to denote values and fields.

Related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/496

cc @baywet @darrelmiller
