### ISSUE TITLE
Use of `OneOf` and `anyOf` leads to generation errors with AutoREST

### ISSUE THREAD

**Issue by peombwa** [microsoft/OpenAPI.NET.OData#280]
Given `BookingService` entity type with a `defaultPrice` property type of `Edm.Double`:
![image](https://user-images.githubusercontent.com/7061532/190524727-d01c6165-83fa-427b-8698-138996bdacc3.png)

In `v1.1.0` we generate the property with `OneOf` with the following schemas, yet only the `type: number` with a `format: double` is valid according to the CSDL above:
![image](https://user-images.githubusercontent.com/7061532/190524908-aa3815e6-7b9c-4fa2-aa6c-bc703d728e58.png)

This leads to generation errors since AutoREST does not currently support `OneOf`:
``` powershell
@autorest\remodeler\dist\plugin-remodeler.js - FAILURE  {} Error: Invalid Reference schemas:975 -- #/components/schemas/schemas:975
```
### Expected result
Only the property types present in the CSDL metadata should be generated in the OpenAPI:
``` yml
defaultPrice:
    type: number
    description: The default monetary price for the service.
    format: double
```

Please note that AutoREST does not currently support `OneOf`/`AnyOf`. See https://github.com/Azure/autorest/issues/4118.
