### ISSUE TITLE
Duplicate operation ids for functions overloads

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#383]
OData functions with overloads get the same operationId resulting in an invalid OpenAPI document.
Functions should contain their parameters in the OperationId so they don't collide.

### Assemblies affected

1.4.0

### Steps to reproduce

Convert Graph v1. As additionalAccess function has multiple overloads, we get colliding operation ids, which is invalid for OpenAPI.

### Expected result

Functions overloads to have different operation ids

### Actual result

- `/identityGovernance/entitlementManagement/assignments/additionalAccess(accessPackageId=''{accessPackageId}'',incompatibleAccessPackageId=''{incompatibleAccessPackageId}'')`
- `/identityGovernance/entitlementManagement/assignments/additionalAccess()`

Both have the same operation id

### Additional detail

Related #382 #324 https://github.com/microsoftgraph/msgraph-metadata/issues/289 https://github.com/APIs-guru/openapi-directory/issues/1053

**Comment by irvinesunday** [comment]
The initial [implementation](https://github.com/microsoft/OpenAPI.NET.OData/blob/0038a560f7c90d554c34b7e2605a03461113c7c4/src/Microsoft.OpenApi.OData.Reader/Edm/EdmModelExtensions.cs#L196-L199) was set up to append a hash suffix to the operation ids in cases of overloaded functions, for example

```YAML
/identityGovernance/entitlementManagement/assignments/microsoft.graph.additionalAccess():
    description: Provides operations to call the additionalAccess method.
    get:
      tags:
        - identityGovernance.Functions
      summary: Invoke function additionalAccess
      operationId: identityGovernance.entitlementManagement.assignments.additionalAccess-1164
```

The above implementation needs to be updated to be able to read `BindingParameter` types of collection.
