### ISSUE TITLE
Alternate keys are duplicated across paths in the same segment are also have alternate keys. 

### ISSUE THREAD

**Issue by andrueastman** [microsoft/OpenAPI.NET.OData#414]
Latest beta openApi metadata yeilds the following errors when parsed with the openApi library.

```shell
fail: Kiota.Builder.KiotaBuilder[0]
      OpenAPI error: #/paths/~1applications(appId='{appId}')/parameters/1/in - Declared path parameter "uniqueName" needs to be defined as a path parameter at either the path or operation level
fail: Kiota.Builder.KiotaBuilder[0]
      OpenAPI error: #/paths/~1applications(uniqueName='{uniqueName}')/parameters/0/in - Declared path parameter "appId" needs to be defined as a path parameter at either the path or operation level
```

Taking a look at the paths `'/applications(appId=''{appId}'')'` 

```yaml
  '/applications(appId=''{appId}'')':
    description: Provides operations to manage the collection of application entities.
    get:
....
    parameters:
      - name: appId
        in: path
        description: Alternate key of application
        required: true
        schema:
          type: string
          nullable: true
      - name: uniqueName
        in: path
        description: Alternate key of application
        required: true
        schema:
          type: string
          nullable: true
```

Taking a look at the path `'/applications(uniqueName=''{uniqueName}'')'`

```yaml
  '/applications(uniqueName=''{uniqueName}'')':
    description: Provides operations to manage the collection of application entities.
    get:
...
    parameters:
      - name: appId
        in: path
        description: Alternate key of application
        required: true
        schema:
          type: string
          nullable: true
      - name: uniqueName
        in: path
        description: Alternate key of application
        required: true
        schema:
          type: string
          nullable: true
```

The path parameters are duplicated accross the alternate key paths of the 2 paths. The `'/applications(appId=''{appId}'')'` should only have one path parameter(i.e. `appId`) while `'/applications(uniqueName=''{uniqueName}'')'` should only have `uniqueName`.
