### ISSUE TITLE
[Fix] Update `operationId`s of navigation property paths with OData type cast segments

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET.OData#442]
Recently, we enable the expansion of derived types navigation properties [here](https://github.com/microsoftgraph/msgraph-metadata/pull/476).
This created paths like below:

```YAML
'/deviceAppManagement/mobileApps/{mobileApp-id}/microsoft.graph.androidStoreApp/categories/{mobileAppCategory-id}':
    description: Provides operations to manage the categories property of the microsoft.graph.mobileApp entity.
    get:
      tags:
        - deviceAppManagement.mobileApp
      summary: Get categories from deviceAppManagement
      description: The list of categories for this app.
      operationId: deviceAppManagement.mobileApps.GetCategories
```
Since we only generate operationIds of navigation property paths based on the navigation property segments, we end up with duplicate operationIds for 'similar' navigation property paths which only differ on the OData type cast segment, e.g.:

```YAML
'/deviceAppManagement/mobileApps/{mobileApp-id}/microsoft.graph.iosLobApp/categories/{mobileAppCategory-id}':
    description: Provides operations to manage the categories property of the microsoft.graph.mobileApp entity.
    get:
      tags:
        - deviceAppManagement.mobileApp
      summary: Get categories from deviceAppManagement
      description: The list of categories for this app.
      operationId: deviceAppManagement.mobileApps.GetCategories
```

We need to update the `operationId`s so as to include the OData type cast segment name to differentiate the above two scenarios.
