### ISSUE TITLE
Collections of primitive types should be nullable

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#466]
collection of primitive types (properties that are collection(string) or another primitive type) should be nullable.

### Steps to reproduce

```http
GET /me?$select=displayName
```

Results in

```JSON
{"displayName": "Jane Doe"}
```

### Expected result

The emitted schema should be
```yaml
imAddresses:
  type: array
  nullable: true
  items:
    type: string
    nullable: true
```

which would validate the payload.

### Actual result

But the emitted schema for user is

```yaml
imAddresses:
  type: array
  items:
    type: string
    nullable: true
```

which doesn't validate the above payload.
