### ISSUE TITLE
Optimization - reusable components for orderby/expand/select query parameters

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#612]
Since #197 was implemented through #499, we have a big opportunity to make descriptions much smaller.

Effectively all operations now have the same definition for those query parameters when they support it

```yaml
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
```

When the setting it on, we should do the same thing we do for count/top/skip/filter... and have instead

```yaml
 - $ref: '#/components/parameters/expand'
 - $ref: '#/components/parameters/select'
 - $ref: '#/components/parameters/orderby'
```

Which would save a ton of repetition throughout the final description.
