### ISSUE TITLE
orderby/select/expand should be oneOf when UseStringArrayForQueryOptionsSchema is false

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET.OData#615]
Currently we describe

```yaml

parameters:
  - name: $select
    in: query
    style: form
    explode: false
    schema:
      uniqueItems: true
      type: array
      items:
        type: string
        enum:
          - id
          - firstName
          - ....
```

It should instead be

```yaml

parameters:
  - name: $select
    in: query
    style: form
    explode: false
    schema:
      uniqueItems: true
      type: array
      items:
        oneOf:
        - type: string
        - type: string
           enum:
             - id
             - firstName
             - ....
```

This is because for any navigation property you can write `$select=navProperty($expand=subproperty)` and we don't want to project all possibilities. But we don't want to restrict clients to simply the scalar/first level properties.
