### ISSUE TITLE
Add option to allow not including the examples

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET.OData#68]
The generated examples are not very useful as they don't contain representative values and in some cases the values actually don't match the datatypes so they cause warnings and errors with linting tools.  They also considerably bulk up the output document.

Consider this example.  It doesn't provide any more information than the schema itself.
```
      example:
        serialNumber: string
        totalStorageSpace: integer
        deviceGuardLocalSystemAuthorityCredentialGuardState: '@odata.type': microsoft.graph.deviceGuardLocalSystemAuthorityCredentialGuardState	          
        osBuildNumber: string
        operatingSystemProductType: integer
```

The other consideration is to just stop producing examples completely.  If we keep them we should consider actually generating representative sample values.
